### PR TITLE
Add Ui Mockup

### LINKED ISSUE #41: Update README Ui Mockup

### PR DESCRIPTION
**Pull request by FergusMok**
Fixes #41

### CODE REVIEW

**Review by caipng — CHANGES_REQUESTED** [review]
File name is wrong, should be `Ui.png` instead of `Ui.png.png`. Other than that LGTM!

**Review by chaiwanlin — CHANGES_REQUESTED** [review]
> File name is wrong, should be `Ui.png` instead of `Ui.png.png`. Other than that LGTM!

Same problem as what @caipng stated, otherwise LGTM

**Review by caipng — APPROVED** [review]
LGTM!

**Review by chaiwanlin — APPROVED** [review]
LGTM

**Pull request merged**
