### PR TITLE
Update User Guide for v1.3

### PR DESCRIPTION
**Pull request by FergusMok**

### CODE REVIEW

**Review by chaiwanlin — CHANGES_REQUESTED** [review]
Added in the remove command

**Review by marcusc55 — CHANGES_REQUESTED** [review]
Some changes needed for the `grade` and `dlgrade` commands.

**Review by marcusc55 — APPROVED** [review]
LGTM

**Review by chaiwanlin — DISMISSED** [review]

**Review by uyencfi — APPROVED** [review]
Some changes, otherwise LGTM!

**Pull request merged**
